In [16]:
from pathlib import Path
import pyvista as pv
import numpy as np
from pathlib import Path


from phd_helpers.MeshQuality import check_mesh_quality, mesh_quality_summary

In [23]:
def extract_mesh_regions(mesh):
    """mesh with bone(1) cartilage(2) volumes and bone(-1) cartilage(-2) interface(-3) surfaces"""
    shell_mesh = mesh.extract_cells_by_type(5)
    return {
        'mesh': mesh,

        'shell': shell_mesh.extract_surface(algorithm=None),
        'bone_shell': shell_mesh.extract_cells(np.where(shell_mesh['region_id']==-2)[0], invert=True).extract_surface(algorithm=None),
        'cartilage_shell': shell_mesh.extract_cells(np.where(shell_mesh['region_id']==-1)[0], invert=True).extract_surface(algorithm=None),

        'bone_surf': shell_mesh.extract_cells(np.where(shell_mesh['region_id']==-1)[0]).extract_surface(algorithm=None),
        'cartilage_surf': shell_mesh.extract_cells(np.where(shell_mesh['region_id']==-2)[0]).extract_surface(algorithm=None),
        'interface_surf': shell_mesh.extract_cells(np.where(shell_mesh['region_id']==-3)[0]).extract_surface(algorithm=None),

        'bone_vol': mesh.extract_cells(np.where(mesh['region_id']==1)[0]),
        'cartilage_vol': mesh.extract_cells(np.where(mesh['region_id']==2)[0])
    }

In [27]:
subject, sideL = '14548', 'R'
#subject, sideL = '50007', 'L'
#subject, sideL = '14819', 'R'
bone_arbone = 'tpm-mc1'
id_2d, id_cart, id_3d, id_man = 0, 0, 0, 0

root_dir = '../../MeshPipeline/outputs/testing/testing4'
path = Path(f'{root_dir}/meshes/{subject}{sideL}/{bone_arbone}')

path2D = path / '2Dmesh'
mesh3 = pv.read(path2D / f'bone_remesh-{id_2d}.obj')
mesh2D = pv.read(path2D / f'bone_cartilage_mesh-{id_2d}-{id_cart}.vtp')

path3D = path / '3Dmesh'
#mesh_3D = pv.read(path3D / f'mesh-{id_2d}-{id_cart}-{id_3d}.mesh')
mesh3D = pv.read(path3D / f'mesh-{id_2d}-{id_cart}-{id_3d}.vtu')
#mesh_print_cart = pv.read(path3D / f'3Dprint/cartilage-{id_2d}-{id_cart}-{id_3d}-{id_man}.vtp')
#mesh_print_bone = pv.read(path3D / f'3Dprint/bone-{id_2d}-{id_cart}-{id_3d}-{id_man}.vtp')

mesh_dict = extract_mesh_regions(mesh3D)

#### 3D Mesh quality

In [28]:
qual = check_mesh_quality(mesh3D.extract_cells_by_type(10), 'tet')
mesh_quality_summary(qual, cell_type='tet')

radius_ratio 299/172330 cells outside of acceptable range (0.4, 1.0)
shape 5/172330 cells outside of acceptable range (0.4, 1.0)
aspect_ratio 263/172330 cells outside of acceptable range (1.0, 3.0)
scaled_jacobian 23/172330 cells outside of acceptable range (0.2, 1.0)
aspect_frobenius 280/172330 cells outside of acceptable range (1.0, 2.0)
condition 41/172330 cells outside of acceptable range (1.0, 3.0)

,mean,best,worst,acceptable_range,acceptable_range_pct,bad_cells,95%
metric,,,,,,,
min_angle,50.582867,69.518686,15.023828,"(10, 70.53)",100.000000,0,"(35.09, 69.52)"
max_angle,96.375660,71.537251,157.203761,"(70.53, 170)",100.000000,0,"(71.54, 121.53)"
radius_ratio,0.851246,0.999577,0.209518,"(0.4, 1.0)",99.826496,299,"(0.66, 1.0)"
shape,0.877443,0.999656,0.360059,"(0.4, 1.0)",99.997099,5,"(0.72, 1.0)"
aspect_ratio,1.384924,1.014438,4.321222,"(1.0, 3.0)",99.847386,263,"(1.01, 1.8)"
scaled_jacobian,0.701328,0.989217,0.120218,"(0.2, 1.0)",99.986654,23,"(0.48, 0.99)"
aspect_frobenius,1.151473,1.000344,2.777319,"(1.0, 2.0)",99.837521,280,"(1.0, 1.39)"
condition,1.163907,1.000343,3.744545,"(1.0, 3.0)",99.976208,41,"(1.0, 1.45)"

In [ ]:
# og
qual = check_mesh_quality(mesh3D.extract_cells_by_type(10), 'tet')
mesh_quality_summary(qual, 'tet')

radius_ratio 308/172260 cells outside of acceptable range (0.4, 1.0)
shape 6/172260 cells outside of acceptable range (0.4, 1.0)
aspect_ratio 276/172260 cells outside of acceptable range (1.0, 3.0)
scaled_jacobian 24/172260 cells outside of acceptable range (0.2, 1.0)
aspect_frobenius 281/172260 cells outside of acceptable range (1.0, 2.0)
condition 36/172260 cells outside of acceptable range (1.0, 3.0)

,mean,best,worst,acceptable_range,acceptable_range_pct,bad_cells,95%
metric,,,,,,,
min_angle,50.612190,69.649897,15.038010,"(10, 70.53)",100.000000,0,"(35.21, 69.65)"
max_angle,96.325232,71.281885,157.134766,"(70.53, 170)",100.000000,0,"(71.28, 121.31)"
radius_ratio,0.851625,0.999307,0.210332,"(0.4, 1.0)",99.821201,308,"(0.66, 1.0)"
shape,0.877765,0.999469,0.360891,"(0.4, 1.0)",99.996517,6,"(0.72, 1.0)"
aspect_ratio,1.384022,1.011847,4.301057,"(1.0, 3.0)",99.839777,276,"(1.01, 1.8)"
scaled_jacobian,0.701633,0.989217,0.120632,"(0.2, 1.0)",99.986068,24,"(0.48, 0.99)"
aspect_frobenius,1.150931,1.000532,2.770921,"(1.0, 2.0)",99.836874,281,"(1.0, 1.39)"
condition,1.163193,1.000529,3.739420,"(1.0, 3.0)",99.979101,36,"(1.0, 1.44)"
distortion,1.000000,1.000000,1.000000,"(0.5, 1.0)",100.000000,0,"(1.0, 1.0)"

In [26]:
mesh_dict['shell'].plot(scalars='region_id', show_edges=True)

Widget(value='<iframe src="http://localhost:57897/index.html?ui=P_0x35daca4e0_6&reconnect=auto" class="pyvista…

#### 2D mesh

In [10]:
mesh2D.plot(show_edges=True, scalars='region_id')

Widget(value='<iframe src="http://localhost:57897/index.html?ui=P_0x348621220_2&reconnect=auto" class="pyvista…

#### Cartilage height 2D mesh

In [29]:
cart_surf = mesh2D.extract_cells(np.where(mesh2D['region_id']==2)[0])
bone_shell = mesh2D.extract_cells(np.where(mesh2D['region_id']==2)[0], invert=True).extract_surface(algorithm=None)
cart_height = cart_surf.compute_implicit_distance(bone_shell)['implicit_distance']

pl = pv.Plotter()
pl.add_mesh(cart_surf, scalars=cart_height)
pl.add_mesh(bone_shell, color='white')
pl.show()

Widget(value='<iframe src="http://localhost:57897/index.html?ui=P_0x35dac8ad0_7&reconnect=auto" class="pyvista…

# Printing

In [47]:
pl = pv.Plotter()
pl.add_mesh(mesh_print_bone, color='teal', scalars='repaired')
pl.add_mesh(mesh_print_cart, color='beige', scalars='repaired')
pl.show()

Widget(value='<iframe src="http://localhost:51945/index.html?ui=P_0x32ea4be30_5&reconnect=auto" class="pyvista…

In [131]:
pose = 'jar'
bone_instron = pv.read(path / f'3Dmesh/3Dprint/InstronPrint/{bone}-boneJig-{pose}.vtp')
cart_instron = pv.read(path / f'3Dmesh/3Dprint/InstronPrint/{bone}-cartilage-{pose}.vtp')

import trimesh
instron_tmesh = trimesh.load(path / f'3Dmesh/3Dprint/InstronPrint/{bone}Print-{pose}.3mf')

In [132]:
pl = pv.Plotter()
pl.add_mesh(bone_instron)
pl.add_mesh(cart_instron, color='beige')
pl.show()

Widget(value='<iframe src="http://localhost:64307/index.html?ui=P_0x4565ec2f0_66&reconnect=auto" class="pyvist…

In [133]:
print("Loaded geometry keys:", list(instron_tmesh.geometry.keys()))
instron_tmesh.show()

Loaded geometry keys: ['boneJig', 'cartilage']

# Interference

### testing 3
 - origninal params
 - tpm-mc1

In [ ]:
# interference after cartilage generation

import os
import json
from pathlib import Path

interference_path = Path('testing3/reports/interference.jsonl')
bad_subs = []
with open(interference_path, 'r') as f:
    for line in f:
        bad_subs.append(json.loads(line)['subject'])

all_subs = [x.strip('.csv') for x in os.listdir(interference_path.parent.parent / 'meshes')]
good_subs = [x for x in all_subs if x not in bad_subs]

print('bad ', len(bad_subs), bad_subs)
print('good', len(good_subs), good_subs)

bad  11 ['14613R', '16276L', '50090R', '15357R', '15285R', '50033L', '15358R', '15284R', '15882R', '15282R', '50061R']
good 35 ['14818R', '14874R', '22306R', '50000R', '50049R', '50034R', '15006R', '50017L', '15441R', '14827L', '14726R', '15294R', '50021R', '50027L', '50008L', '14548R', '14873R', '15737R', '14685R', '50045R', '50006R', '50029R', '50020R', '50018L', '50037L', '14727R', '50014R', '50019R', '50053R', '50016L', '50024R', '50007L', '50001R', '14819R', '15283R']

In [ ]:
# original mesh interference check - before any mesh processing

from phd_helpers.helpers2 import bone_pair_pose_intersection

bone_pairs = ['tpm-mc1']
poses = ['adduction','abduction','flexion','extension','pinch','grasp','jar','neutral']
safe_subs = bone_pair_pose_intersection(bone_pairs, poses,'../checkInterference2').to_list()

no_safe_subs = [x for x in all_subs if x not in safe_subs]
print('bad ', len(no_safe_subs), no_safe_subs)
print('good', len(safe_subs), safe_subs)

bad  16 ['15282R', '14874R', '15006R', '16276L', '15882R', '50090R', '15294R', '15358R', '15285R', '15737R', '50061R', '15284R', '14727R', '50033L', '15357R', '14819R']
good 30 ['14873R', '50017L', '22306R', '50037L', '14613R', '50019R', '50034R', '14827L', '50016L', '50014R', '50027L', '14818R', '50029R', '50007L', '14726R', '50045R', '50053R', '50024R', '50049R', '50006R', '14548R', '15441R', '50008L', '50001R', '50021R', '14685R', '15283R', '50018L', '50020R', '50000R']

In [31]:
shared = np.intersect1d(bad_subs, no_safe_subs)
diff = np.setxor1d(bad_subs, no_safe_subs)
print('Shared', len(shared), shared)
print('Diff  ', len(diff), diff)

Shared 10 ['15282R' '15284R' '15285R' '15357R' '15358R' '15882R' '16276L' '50033L'
 '50061R' '50090R']
Diff   7 ['14613R' '14727R' '14819R' '14874R' '15006R' '15294R' '15737R']